### ISSUE TITLE
Push trigger debugging

### ISSUE THREAD

**Issue by sudarsanan-krishnan** [logicappsio/EventHubAPI#1]
Hello, how do I debug the event hub when i use it as a push trigger? I haven't been able to trigger the logic app when an event arrives. I am using the same connection parameters in a different console app and it receives events, but the trigger doesn't seem to respond. 

![image](https://cloud.githubusercontent.com/assets/16565013/12658451/01b56762-c5be-11e5-9d4a-11141e428591.png)

Also, what does the recurrence do? Why does the logic app need to check within this interval if its a "push" trigger? And whats the false condition for?

Thanks,
Sudarsanan.

**Comment by jeffhollan** [comment]
In the Logic Apps Portal pane you should see a button called "Trigger History" which will show you when the trigger is registering with the service - and then if it fires you should see it show in your Workflow history.

The recurrence is how often the Logic Apps Engine will talk to the API to "register" a listener.  In other words every 'minute' in this case Logic Apps goes to the API App and says "hey I want you to listen to this event hub with these settings, and as soon as you have something here's how to callback to me."  So if you change a setting, it will take until the trigger 'recurs' to register that with the listener API.

For this particularly I would try creating a seperate consumer group.  I don't know if I've tried putting $default in the parameter, and wondering if that may be why?

**Comment by jeffhollan** [comment]
Discovered the issue was with parsing the event hub message as a JObject - which would error when the message was actually an Array (or anything other than a valid JObject).  Committed change to parse as JToken
